import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href='/compound-components'>compound-components</Link>
          </li>
          <li>
            <Link href='/flexible-compound-components'>
              flexible-compound-components
            </Link>
          </li>
          <li>
            <Link href='/prop-getters'>prop-getters</Link>
          </li>
          <li>
            <Link href='/state-reducer'>state-reducer</Link>
          </li>
          <li>
            <Link href='/control-props'>control-props</Link>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
